site_name: buildko89 Documents
theme:
  name: material
  custom_dir: overrides  # カスタム設定を置くフォルダ
  features:
    - navigation.expand
    - navigation.tabs

# プラグインの設定
plugins:
  - search
  - awesome-pages  # これでフォルダ構成が自動的にメニューになります

# 外部CSSの登録
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - ...